# -*- coding: utf-8 -*-
"""What each organisation actually works on.

The entries have facet tags describing what a company IS - a seed major, a
contract laboratory, a trade body. Nothing in them says what organism it works
on, which is the first thing most readers want to filter by.

This file adds that, by hand, keyed on entry name. It is deliberately separate
from ind1.py-ind23.py so it can be filled in batches without touching 23 modules
and re-running the risk of a bad splice through them.

RULES FOLLOWED HERE

An entry lists every organism group it genuinely works on, not the one it is
best known for. Bayer is maize AND soy AND cotton AND canola AND vegetables;
filing it under maize alone is the exact failure that made a text-scraped
version unusable.

An entry with no clear organism gets an empty list rather than a guess. A
patent office, an index fund and a lobbying register do not work on an organism,
and inventing one for them would put noise in every filter.

GROUPS match the release-side classifier in index.html, so a reader moving
between the two layers meets the same words:

    food_crops  vegetables  fibre  forage  trees
    livestock   fish        lab_animals
    insects     microbes    viruses
    human       none
"""

# REGENERATED FROM THE MAP.
#
# This file held 46 of the 519 entries while index.html carried the completed
# work for all of them, so every rebuild of industry_points.json dropped the
# organism from 473 organisations. The file is the source and the map is
# derived, so the file is the thing that had to be brought up to date - it is
# rewritten here from the entries the map was already drawing, in the module
# order the merger produces.
#
# 519 entries. 41 work on no organism at all and carry an empty list, which is a
# statement rather than a gap: a patent register, an index fund and a lobbying
# record do not work on an organism, and inventing one for them would put noise
# in every filter.

SPECIES = {
    "Bayer Crop Science": ["food_crops", "fibre", "vegetables", "forage"],
    "Corteva Agriscience": ["food_crops", "fibre", "vegetables"],
    "Bayer — investor filings": [],
    "Corteva — CRISPR licensing framework": ["food_crops"],
    "Ginkgo Bioworks": ["microbes"],
    "Inari Agriculture": ["food_crops"],
    "Twist Bioscience": ["microbes", "viruses"],
    "Integrated DNA Technologies (Danaher)": ["microbes"],
    "Illumina": [],
    "Addgene": ["microbes", "viruses"],
    "Charles River Laboratories": ["lab_animals", "fish"],
    "Labcorp Drug Development (formerly Covance)": ["lab_animals", "human"],
    "Syngenta Group": ["food_crops", "fibre", "vegetables"],
    "Syngenta — seedcare & seeds portfolio": ["food_crops", "fibre"],
    "BASF Agricultural Solutions": ["food_crops", "fibre", "microbes"],
    "Rijk Zwaan": ["vegetables"],
    "Limagrain / Vilmorin": ["food_crops", "vegetables"],
    "Oxford Nanopore Technologies": [],
    "BGI Group": ["human"],
    "The Jackson Laboratory": ["lab_animals"],
    "Taconic Biosciences": ["lab_animals"],
    "Envigo / Inotiv": ["lab_animals"],
    "Acceligen (Recombinetics)": ["livestock"],
    "AquaBounty Technologies": ["fish"],
    "ViaGen Pets & Equine": ["livestock", "lab_animals"],
    "Target Malaria": ["insects"],
    "Pivot Bio": ["microbes", "food_crops"],
    "Colossal Biosciences": ["livestock", "lab_animals"],
    "Living Carbon": ["trees"],
    "Vertex / CRISPR Therapeutics — Casgevy": ["human"],
    "ClinicalTrials.gov": ["human"],
    "Orchid Health": ["human"],
    "CDC ART clinic data": ["human"],
    "Gates Foundation — committed grants database": [],
    "DARPA — Biological Technologies Office": ["insects", "microbes", "food_crops"],
    "BIO — Biotechnology Innovation Organization": [],
    "ISAAA — GM approval database": ["food_crops", "fibre"],
    "CLEA Japan / Japan SLC": ["lab_animals"],
    "Sooam Biotech": ["lab_animals", "livestock"],
    "Oxitec": ["insects"],
    "HFEA — licensed clinic register": ["human"],
    "Suzano / FuturaGene": ["trees"],
    "Novartis — gene therapy": ["human"],
    "IVIRMA Global": ["human"],
    "CropLife International": ["food_crops", "fibre"],
    "OECD BioTrack": ["food_crops", "fibre", "vegetables"],
    "Bayer — Climate FieldView & digital farming": ["food_crops", "fibre"],
    "Benson Hill": ["food_crops"],
    "Pairwise": ["vegetables", "food_crops"],
    "Broad Institute — CRISPR patent estate": [],
    "Synthego": ["microbes", "human"],
    "Amyris": ["microbes"],
    "Thermo Fisher Scientific": [],
    "GenScript": ["microbes", "viruses"],
    "ATCC": ["microbes", "viruses", "human"],
    "Mutant Mouse Resource & Research Centers": ["lab_animals"],
    "Agragene": ["insects"],
    "Indigo Ag": ["microbes", "food_crops"],
    "Bluebird bio": ["human"],
    "Cooper Surgical — fertility": ["human"],
    "California Cryobank / Generate Life Sciences": ["human"],
    "ARCH Venture Partners": [],
    "Wellcome Trust": [],
    "KeyGene": ["food_crops", "vegetables"],
    "Groupe Roullier / seed & input distribution": ["food_crops", "forage"],
    "Janvier Labs": ["lab_animals"],
    "Oxford Biomedica": ["viruses", "human"],
    "Genus / PIC": ["livestock"],
    "Lonza": ["microbes", "human"],
    "AquaGen": ["fish"],
    "National Medical Products Administration — gene therapy": ["human"],
    "Mahyco / Maharashtra Hybrid Seeds": ["fibre", "vegetables"],
    "Department of Biotechnology": ["food_crops", "human", "microbes"],
    "Syngenta Group China": ["food_crops", "fibre"],
    "Chinese Academy of Agricultural Sciences": ["food_crops", "livestock"],
    "Embrapa": ["food_crops", "forage", "livestock"],
    "CTNBio — national biosafety commission": ["food_crops", "trees", "insects"],
    "Bioceres Crop Solutions": ["food_crops"],
    "BioNTech": ["human"],
    "Evotec": ["human", "lab_animals"],
    "Sanatech Seed": ["vegetables"],
    "Regional Fish Institute": ["fish"],
    "Evogene": ["food_crops"],
    "Toolgen": ["human", "food_crops"],
    "Singapore Food Agency — novel food approvals": ["microbes", "livestock"],
    "Corbion": ["microbes"],
    "Novonesis (Novozymes / Chr. Hansen)": ["microbes"],
    "Office of the Gene Technology Regulator — GMO Record": ["food_crops", "fibre", "insects"],
    "Nufarm": ["food_crops", "fibre"],
    "Canadian Food Inspection Agency — PNT decisions": ["food_crops", "fibre", "forage"],
    "Revive & Restore": ["livestock", "lab_animals"],
    "San Diego Zoo Wildlife Alliance — Frozen Zoo": ["livestock", "lab_animals"],
    "American Chestnut Foundation — Darling 58": ["trees"],
    "Colossal — Form Bio spin-out": [],
    "MosquitoMate": ["insects"],
    "Ginkgo Bioworks — agricultural biologicals": ["microbes", "food_crops"],
    "Elemental Enzymes / biologicals sector": ["microbes", "food_crops"],
    "Genus — PRRS-resistant pig approval": ["livestock"],
    "GloFish": ["fish"],
    "Trans Ova Genetics": ["livestock"],
    "Progyny": ["human"],
    "Genomic Prediction / LifeView": ["human"],
    "Society for Assisted Reproductive Technology": ["human"],
    "Wolbachia — World Mosquito Program": ["insects"],
    "Baillie Gifford / growth capital in biotech": [],
    "Livestock Improvement Corporation": ["livestock"],
    "Eugin Group": ["human"],
    "Cryos International": ["human"],
    "CIBIOGEM": ["food_crops"],
    "Grupo Bimbo": ["food_crops"],
    "Executive Council for GMOs — Department of Agriculture": ["food_crops", "fibre"],
    "Pannar Seed (Corteva)": ["food_crops"],
    "National Biosafety Management Agency": ["food_crops", "fibre"],
    "Kenya National Biosafety Authority": ["food_crops", "fibre"],
    "Illumina Italy / Ferrara sequencing hub": [],
    "Selvita": ["human", "lab_animals"],
    "Syngene International": ["human", "lab_animals"],
    "Bharat Biotech": ["human", "viruses"],
    "WuXi AppTec": ["human", "lab_animals"],
    "Dabeinong Biotechnology": ["food_crops"],
    "Charoen Pokphand Group": ["livestock", "food_crops", "fish"],
    "Nutreco / Skretting": ["fish", "livestock", "microbes"],
    "JBS": ["livestock"],
    "Colossal — thylacine programme partners": ["livestock", "lab_animals"],
    "Australian Frozen Zoo / CryoDiversity": ["livestock", "lab_animals"],
    "Understanding Animal Research": ["lab_animals"],
    "Home Office — animals in science statistics": ["lab_animals", "fish"],
    "Federal Research Center for Animal Husbandry": ["livestock"],
    "Ministry of Agriculture and Forestry — biosafety board": ["food_crops"],
    "Ministry of Agrarian Policy and Food": ["food_crops"],
    "PT Perkebunan Nusantara / sugarcane biotechnology": ["food_crops"],
    "Ministry of Agriculture and Environment — biosafety": ["food_crops"],
    "ICA — Instituto Colombiano Agropecuario": ["fibre", "food_crops"],
    "SLU — Swedish University of Agricultural Sciences": ["food_crops", "trees"],
    "Solar Foods": ["microbes"],
    "Teagasc": ["livestock", "forage", "food_crops"],
    "Cyagen": ["lab_animals"],
    "National Primate Research Centers": ["lab_animals"],
    "Bachem": ["human"],
    "Samsung Biologics": ["human"],
    "Virtus Health": ["human"],
    "Israeli fertility system — Ministry of Health": ["human"],
    "Predator Free 2050 — genetic tools debate": ["lab_animals"],
    "Sovereign wealth investment in agrifood technology": [],
    "National Biosafety Centre — Ministry of Climate Change": ["fibre", "food_crops"],
    "Bangladesh Agricultural Research Institute — Bt brinjal": ["vegetables"],
    "Ethiopian Environment Protection Authority — biosafety": ["fibre", "food_crops"],
    "National Biosafety Authority Ghana": ["food_crops"],
    "Gabinete Nacional de Bioseguridad": ["food_crops"],
    "SENAVE — seed and plant health service": ["food_crops"],
    "SAG — Servicio Agrícola y Ganadero": ["food_crops", "vegetables"],
    "Ministerio de Agricultura — GM cultivation register": ["food_crops"],
    "Direção-Geral de Alimentação e Veterinária": ["food_crops"],
    "Ministry of Agriculture — biotechnology": ["food_crops"],
    "Agricultural Genetic Engineering Research Institute": ["food_crops"],
    "Nuseed / Nufarm omega-3 canola": ["fibre", "fish"],
    "Health Canada — novel food decisions": ["food_crops", "vegetables"],
    "Aldevron (Danaher)": ["microbes", "human"],
    "Pacific Biosciences": [],
    "Bio-Rad Laboratories": [],
    "Intellia Therapeutics": ["human"],
    "Sarepta Therapeutics": ["human"],
    "FDA — cellular & gene therapy approvals": ["human"],
    "Alliance for Regenerative Medicine": ["human"],
    "Flagship Pioneering": [],
    "USDA NIFA — grant database": [],
    "Verily — Debug programme": ["insects"],
    "Greenlight Biosciences": ["insects", "food_crops"],
    "Genomics England": ["human"],
    "Roche / Genentech": ["human"],
    "Leaps by Bayer": [],
    "Oxitec do Brasil": ["insects"],
    "WuXi Biologics Ireland": ["human"],
    "Lonza Singapore / biologics cluster": ["human", "microbes"],
    "Shanghai Model Organisms Center": ["lab_animals"],
    "Chinese assisted reproduction sector — NHC licensing": ["human"],
    "National Biosafety Board Malaysia": ["insects", "food_crops"],
    "Ministerio del Ambiente — moratoria GMO": ["food_crops", "vegetables"],
    "AGES — Austrian Agency for Health and Food Safety": ["food_crops"],
    "Ministry of the Environment — GMO register": ["food_crops"],
    "Centro de Ingeniería Genética y Biotecnología": ["human", "microbes"],
    "Comité Nacional de Bioseguridad": ["food_crops"],
    "Ministerio del Ambiente — bioseguridad": ["food_crops"],
    "Comisión Técnica Nacional de Bioseguridad": ["food_crops"],
    "National Environment Management Council": ["food_crops", "fibre"],
    "National Biosafety Authority Zambia": ["food_crops"],
    "Ministry of Rural Development and Food": ["food_crops"],
    "Ministry of Agriculture — GMO-free constitutional provision": ["food_crops"],
    "Office National de Sécurité Sanitaire des Produits Alimentaires": ["food_crops"],
    "Food and Drug Administration — GM food registration": ["food_crops"],
    "Saudi Food and Drug Authority — GM food rules": ["food_crops"],
    "International Rice Research Institute — Golden Rice": ["food_crops"],
    "Norwegian Biotechnology Advisory Board": ["insects", "human", "fish"],
    "Rewriting Extinction / genetic biocontrol programmes": ["lab_animals", "insects"],
    "Nature Conservancy — biotechnology in conservation": ["trees", "insects", "lab_animals"],
    "Wellcome Leap": ["human"],
    "China National Seed Group (Syngenta / Sinochem)": ["food_crops"],
    "European Bioinformatics Institute — model organism databases": ["lab_animals", "microbes"],
    "USDA APHIS — annual research facility reports": ["lab_animals"],
    "Charles River — global site network": ["lab_animals", "fish"],
    "Jackson Laboratory — Bar Harbor": ["lab_animals"],
    "Wisconsin National Primate Research Center": ["lab_animals"],
    "Inotiv — facility network": ["lab_animals"],
    "Home Office — licensed establishments": ["lab_animals", "fish"],
    "The Francis Crick Institute — animal research": ["lab_animals"],
    "German Primate Center (DPZ)": ["lab_animals"],
    "Biomedical Primate Research Centre": ["lab_animals"],
    "Charles River / Janvier — European breeding sites": ["lab_animals"],
    "Guangdong / Hainan primate breeding sector": ["lab_animals"],
    "Cyagen — Suzhou and Santa Clara facilities": ["lab_animals"],
    "RIKEN BioResource Research Center": ["lab_animals", "microbes"],
    "Committee for Control and Supervision of Experiments on Animals": ["lab_animals"],
    "European Commission — ALURES animal use database": ["lab_animals", "fish"],
    "Arnold & Porter — agricultural biotechnology practice": [],
    "Covington & Burling — food and drug regulatory": [],
    "US Patent and Trademark Office — patent full-text search": [],
    "Patent Trial and Appeal Board": [],
    "Bayer Crop Science — divisional leadership": ["food_crops", "fibre"],
    "Broad Institute — CRISPR inventors and the patent record": [],
    "Innovative Genomics Institute — Jennifer Doudna": ["food_crops", "human"],
    "Colossal Biosciences — founders and scientific advisers": ["livestock", "lab_animals"],
    "European Patent Office — opposition register": ["food_crops", "vegetables"],
    "No Patents on Seeds": ["food_crops", "vegetables", "livestock"],
    "EU Transparency Register — biotechnology lobbying": [],
    "Euroseeds": ["food_crops", "vegetables"],
    "He Jiankui — the germline case and its aftermath": ["human"],
    "Rothamsted Research": ["food_crops", "fibre"],
    "Syngenta — sustainability and regulatory reporting": ["food_crops", "fibre"],
    "OECD — Working Party on Biotechnology": ["food_crops"],
    "FAO — biotechnology and biosafety": ["food_crops"],
    "IQVIA": ["human"],
    "Parexel": ["human"],
    "Catalent": ["human"],
    "ICON plc — site and patient networks": ["human"],
    "Fujifilm Diosynth Biotechnologies": ["human", "microbes"],
    "ClinicalTrials.gov — sponsor and site search": ["human"],
    "US Fertility": ["human"],
    "Kindbody": ["human"],
    "Cooper Surgical — culture media recall": ["human"],
    "Society for Reproductive Endocrinology and Infertility": ["human"],
    "Pharmaron": ["human", "lab_animals"],
    "BGI Genomics — clinical and prenatal testing": ["human"],
    "Celltrion": ["human"],
    "Serum Institute of India": ["human", "viruses"],
    "HFEA — treatment add-ons ratings": ["human"],
    "Care Fertility": ["human"],
    "Spanish Fertility Society — national registry": ["human"],
    "Cross-border surrogacy and gamete brokerage": ["human"],
    "Monash IVF": ["human"],
    "Blackstone Life Sciences": [],
    "Novo Holdings": [],
    "SEC EDGAR — full-text search": [],
    "Open Philanthropy — biosecurity and science funding": ["microbes", "viruses"],
    "Sterile Insect Technique programmes — IAEA and national partners": ["insects"],
    "EPA — biopesticide and plant-incorporated protectant registrations": ["food_crops", "fibre"],
    "Recombinant DNA Advisory Committee — archive": ["microbes", "human"],
    "Alnylam Pharmaceuticals": ["human"],
    "FDA — intentional genomic alterations in animals": ["livestock", "fish"],
    "Hendrix Genetics": ["livestock", "fish"],
    "International Gene Synthesis Consortium": ["microbes", "viruses"],
    "Benchling": [],
    "Codex DNA / Telesis Bio": ["microbes", "viruses"],
    "Wellcome Sanger Institute": ["human", "lab_animals", "microbes"],
    "Nature's SAFE": ["livestock", "lab_animals"],
    "Moscamed Brasil": ["insects"],
    "Topigs Norsvin": ["livestock"],
    "Mowi": ["fish"],
    "Australian Frozen Zoo — threatened species cryobanking": ["livestock", "lab_animals"],
    "KWS SAAT": ["food_crops"],
    "DLF Seeds": ["forage"],
    "Groupe Florimond Desprez": ["food_crops"],
    "Sakata Seed": ["vegetables"],
    "Bucher / agricultural machinery and data": ["food_crops"],
    "WHO — human genome editing governance framework": ["human"],
    "Beam Therapeutics": ["human"],
    "Prime Medicine": ["human"],
    "Arcadia Biosciences": ["food_crops"],
    "Element Biosciences": [],
    "Ultima Genomics": [],
    "New England Biolabs": ["microbes"],
    "Tropic Biosciences": ["vegetables", "food_crops"],
    "African Union — continental biosafety and biotechnology policy": ["food_crops", "fibre"],
    "Ministry of Agriculture — GMO prohibition": ["food_crops"],
    "Ministry of Environment and Water — GMO register": ["food_crops"],
    "Sri Lanka — food labelling and import control": ["food_crops"],
    "SEARCA — regional biotechnology information": ["food_crops"],
    "Regeneron Genetics Center": ["human"],
    "bluebird bio — the insertional oncogenesis cases": ["human"],
    "Moderna": ["human", "viruses"],
    "Institute for Clinical and Economic Review": ["human"],
    "a16z Bio + Health": [],
    "NIH RePORTER": [],
    "BARDA — Biomedical Advanced Research and Development Authority": ["human", "viruses"],
    "Alliance for Science / Cornell — agricultural biotechnology communications": ["food_crops"],
    "Zoetis": ["livestock", "lab_animals"],
    "Neogen": ["food_crops", "fibre"],
    "Revive & Restore — black-footed ferret cloning": ["lab_animals"],
    "Oxitec — US releases and EPA experimental use permits": ["insects"],
    "CRISPR Therapeutics": ["human"],
    "Temasek — agri-food and life sciences": [],
    "Fonterra": ["livestock"],
    "Guangzhou Wolbaki — mosquito production": ["insects"],
    "African Centre for Biodiversity — corporate research": ["food_crops"],
    "Grain SA and the commercial maize sector": ["food_crops"],
    "INASE — seed royalties and farm-saved seed": ["food_crops"],
    "Federation of Seed Industry of India": ["fibre", "food_crops"],
    "CONAHCYT — native maize and public research": ["food_crops"],
    "IUCN — synthetic biology and biodiversity conservation": ["insects", "lab_animals", "trees"],
    "American Chestnut Research and Restoration Project — SUNY ESF": ["trees"],
    "Colossal Foundation": ["livestock", "lab_animals"],
    "Frozen Ark Project": ["livestock", "lab_animals"],
    "Target Malaria — Imperial College programme record": ["insects"],
    "Cibus": ["food_crops", "fibre"],
    "Bayer — Crop Science product safety summaries": ["food_crops", "fibre"],
    "Center for Food Safety — animal biotechnology litigation": ["fish", "livestock"],
    "Genus — PRRS pig commercialisation record": ["livestock"],
    "Novartis — Zolgensma outcomes-based agreements": ["human"],
    "Alliance for Regenerative Medicine — sector data": ["human"],
    "Thermo Fisher — Patheon and clinical services": ["human"],
    "Advarra": ["human"],
    "AquaChile / Agrosuper": ["fish"],
    "Norwegian Institute of Marine Research — spread monitoring": ["fish"],
    "MHRA — Innovative Licensing and Access Pathway": ["human"],
    "Syncona": ["human"],
    "BGI — MGI Tech instruments": [],
    "European Investment Bank — life sciences lending": [],
    "Enza Zaden": ["vegetables"],
    "Bejo Zaden": ["vegetables"],
    "Beck's Hybrids": ["food_crops"],
    "Corteva — seed applied technologies": ["food_crops", "fibre"],
    "Verve Therapeutics": ["human"],
    "Mammoth Biosciences": ["human", "microbes"],
    "Colossal — Breaking spin-out and IP licensing": ["microbes"],
    "Alpha Genesis": ["lab_animals"],
    "Ace Animals / laboratory dog and cat supply": ["lab_animals"],
    "Fairfax Cryobank / California Cryobank — donor limits": ["human"],
    "Donor Sibling Registry": ["human"],
    "Indian Council of Medical Research — ART regulation": ["human"],
    "UPOV — International Union for the Protection of New Varieties of Plants": ["food_crops", "vegetables"],
    "Codex Alimentarius — foods derived from biotechnology": ["food_crops"],
    "European Food Safety Authority — GMO panel opinions": ["food_crops", "fibre"],
    "Vietnam — GM maize cultivation and feed imports": ["food_crops"],
    "Institute for Agricultural Research, Zaria — Bt cowpea": ["food_crops"],
    "Egypt — wheat import tenders and GM specification": ["food_crops"],
    "Pivot Bio — PROVEN product record": ["microbes", "food_crops"],
    "Marrone / Pro Farm Group": ["microbes", "food_crops"],
    "USDA APHIS — biotechnology regulatory notices": ["food_crops", "fibre", "trees"],
    "ViaGen — Przewalski's horse and endangered species cloning": ["livestock", "lab_animals"],
    "Wildlife Conservation Society — biotechnology position": ["lab_animals", "insects"],
    "Vertex Pharmaceuticals": ["human"],
    "National Marrow Donor Program / NMDP — cell therapy infrastructure": ["human"],
    "Sickle Cell Disease Association of America": ["human"],
    "Fidelity and index funds — passive ownership of the sector": [],
    "Bill & Melinda Gates Agricultural Innovations (Gates Ag One)": ["food_crops"],
    "Rothamsted — GM aphid-repellent wheat trial": ["food_crops"],
    "CSIRO — agricultural biotechnology": ["fibre", "food_crops"],
    "Rhino and wildlife biobanking — BioRescue partners": ["livestock"],
    "PMDA — regenerative medicine conditional approval": ["human"],
    "Chinese state agricultural investment — seed industry revitalisation": ["food_crops"],
    "Aurigene / Dr Reddy's discovery services": ["human", "lab_animals"],
    "SK pharmteco": ["human"],
    "Ministry of Agriculture — GMO cultivation prohibition": ["food_crops"],
    "Malaysian Palm Oil Board — genome programme": ["trees", "food_crops"],
    "S&W Seed Company": ["forage", "food_crops"],
    "Simplot — Innate potatoes": ["food_crops"],
    "J.R. Simplot / McCain — processor specification": ["food_crops"],
    "Perfect Day": ["microbes"],
    "Impossible Foods — soy leghemoglobin": ["microbes", "food_crops"],
    "Conagen": ["microbes"],
    "Charles River — horseshoe crab and LAL supply": ["lab_animals"],
    "Institutional Animal Care and Use Committees — OLAW": ["lab_animals"],
    "Editas Medicine": ["human"],
    "Orchard Therapeutics": ["human"],
    "Euralis / Lidea": ["food_crops"],
    "TMG — Tropical Melhoramento & Genética": ["food_crops"],
    "European Sperm Bank": ["human"],
    "Greek cross-border fertility sector": ["human"],
    "WTO — SPS Committee and biotechnology notifications": ["food_crops"],
    "ISO — biotechnology standards committee": ["microbes", "food_crops"],
    "COMESA — regional biosafety policy": ["food_crops"],
    "Volcani Center — Agricultural Research Organization": ["food_crops", "vegetables"],
    "International Center for Biosaline Agriculture": ["food_crops"],
    "International Potato Center (CIP)": ["food_crops"],
    "Ethiopian Biodiversity Institute": ["food_crops"],
    "Corteva — hybrid wheat programme": ["food_crops"],
    "Bayer — short-stature corn": ["food_crops"],
    "Corteva — Enlist herbicide system": ["food_crops", "fibre"],
    "Ohalo Genetics": ["food_crops"],
    "Syngenta — biologicals and Valagro": ["microbes", "food_crops"],
    "BASF — enzymes and industrial biotechnology": ["microbes"],
    "dsm-firmenich": ["microbes"],
    "Novo Nordisk — recombinant insulin manufacture": ["human", "microbes"],
    "Biocon — biosimilar insulin": ["human", "microbes"],
    "Oxford Nanopore — field sequencing": [],
    "Roslin Institute": ["livestock", "lab_animals"],
    "Yuan Longping High-Tech Agriculture": ["food_crops"],
    "Bioceres / Moolec — molecular farming": ["food_crops"],
    "ISAAA AfriCenter": ["food_crops", "fibre"],
    "Kenya Plant Health Inspectorate Service": ["food_crops"],
    "CIMMYT — maize and wheat genebank": ["food_crops"],
    "MASIPAG": ["food_crops"],
    "American Seed Trade Association": ["food_crops", "vegetables"],
    "Seed Savers Exchange": ["vegetables", "food_crops"],
    "Organic Seed Alliance": ["vegetables", "food_crops"],
    "Scribe Therapeutics": ["human"],
    "Tome Biosciences / large-payload integration": ["human"],
    "iGEM Foundation": ["microbes"],
    "Cyagen / knockout mouse repositories — IMPC": ["lab_animals"],
    "Physicians Committee / animal testing policy": ["lab_animals"],
    "Cargill": ["food_crops", "livestock"],
    "Archer Daniels Midland": ["food_crops"],
    "Nucleus Genomics": ["human"],
    "Society for Assisted Reproductive Technology — clinic outcome reports": ["human"],
    "Foundation for Food & Agriculture Research": ["food_crops", "livestock"],
    "Nuffield Council on Bioethics": ["human", "livestock"],
    "UK Biobank": ["human"],
    "Norwegian Government Pension Fund Global — ethics exclusions": [],
    "Swiss GMO moratorium — Federal Office for the Environment": ["food_crops"],
    "Global 2000 / Friends of the Earth Austria": ["food_crops"],
    "Wageningen University & Research": ["food_crops", "vegetables"],
    "Anastasia / RNAi biopesticide sector": ["insects", "food_crops"],
    "Verily / Debug — automated rearing systems": ["insects"],
    "Ceres Nanosciences / environmental RNA monitoring": ["microbes"],
    "Wisconsin Cryobank / amphibian biobanking": ["lab_animals"],
    "Rewilding and genetic rescue — Florida panther precedent": ["lab_animals"],
    "Medpace": ["human"],
    "Emulate / organ-on-chip": ["human", "lab_animals"],
    "Certara / in-silico trial simulation": ["human", "lab_animals"],
    "Select Sires / bovine genetics cooperatives": ["livestock"],
    "Sexing Technologies / STgenetics": ["livestock"],
    "Royal Botanic Gardens Kew — Millennium Seed Bank": ["trees", "food_crops"],
    "Legal & General / institutional stewardship": [],
    "Lonza — capacity allocation and Moderna": ["human", "microbes"],
    "VikingGenetics": ["livestock"],
    "Testbiotech": ["food_crops", "fibre", "insects"],
    "Corporate Europe Observatory": [],
    "Cobb-Vantress (Tyson Foods)": ["livestock"],
    "Marshall BioResources": ["lab_animals"],
    "Kite Pharma (Gilead)": ["human"],
    "Spark Therapeutics (Roche)": ["human", "viruses"],
    "OrbiMed": [],
    "Bunge": ["food_crops"],
    "Caribou Biosciences": ["human", "food_crops"],
    "Sartorius": ["human", "microbes"],
    "Merck KGaA / MilliporeSigma": ["microbes", "human"],
    "EW Group": ["livestock", "fish"],
    "uniQure": ["human", "viruses"],
    "Vitrolife": ["human"],
    "COFCO International": ["food_crops"],
    "Wilmar International": ["trees", "food_crops"],
    "Secretariat of the Convention on Biological Diversity": ["food_crops", "insects"],
    "Bayer / Ginkgo — Joyn Bio nitrogen fixation": ["microbes", "food_crops"],
    "Jesse Gelsinger and the 1999 trial death — FDA record": ["human", "viruses"],
    "Zymergen / Ginkgo — the collapse and absorption": ["microbes"],
    "Cure Rare Disease and the 2022 trial death": ["human"],
    "Inari — SEEDesign platform": ["food_crops"],
    "GBIRd — Genetic Biocontrol of Invasive Rodents": ["lab_animals"],
    "International Treaty on Plant Genetic Resources (Plant Treaty)": ["food_crops", "vegetables", "forage"],
    "Svalbard Global Seed Vault": ["food_crops", "vegetables", "forage"],
    "Groupe Danone / dairy and ferment supply": ["livestock", "microbes"],
    "Corteva — Pioneer seed production network": ["food_crops"],
    "Elanco Animal Health": ["livestock"],
    "Ohio State / land-grant agricultural extension": ["food_crops", "livestock"],
    "American Farm Bureau Federation": ["food_crops", "livestock"],
    "National Seed Association of India": ["fibre", "food_crops"],
    "BNDES — Brazilian Development Bank": ["livestock", "food_crops"],
    "Ajinomoto": ["microbes"],
    "CJ CheilJedang — fermentation and feed": ["microbes"],
    "Firmenich / flavour and fragrance biotechnology": ["microbes"],
    "Nuffield Farming Scholarships / farmer knowledge networks": ["food_crops", "livestock"],
    "The Non-GMO Project": ["food_crops", "vegetables"],
    "USDA National Organic Program": ["food_crops", "vegetables", "livestock"],
    "Genetic ID / GMO testing laboratories": ["food_crops", "fibre"],
    "Munich Re / agricultural and biotechnology risk": ["food_crops", "livestock"],
    "Koppert Biological Systems": ["insects", "microbes"],
    "Bejo / Rijk Zwaan seed testing and ISTA certification": ["food_crops", "vegetables"],
    "SGS — inspection and certification": ["food_crops", "fibre"],
    "Bundessortenamt — variety registration": ["food_crops", "vegetables"],
    "GeneWatch UK": ["food_crops", "insects", "human"],
    "Confédération paysanne / farmer seed movements": ["food_crops", "vegetables"],
    "African Biodiversity Network / farmer seed systems": ["food_crops"],
    "Navdanya / seed sovereignty movement": ["food_crops", "vegetables"],
    "Defense Threat Reduction Agency": ["microbes", "viruses"],
    "Intelligence Advanced Research Projects Activity — biology programmes": ["microbes", "viruses"],
    "NTI | bio — Nuclear Threat Initiative": ["microbes", "viruses"],
    "Defence Science and Technology Laboratory — Porton Down": ["microbes", "viruses"],
    "Vector State Research Centre of Virology and Biotechnology": ["viruses"],
    "National Center for Biotechnology of Kazakhstan": ["food_crops", "livestock"],
    "Center of Genomics and Bioinformatics": ["fibre"],
    "Council for Scientific and Industrial Research — Ghana": ["food_crops"],
    "Institut Sénégalais de Recherches Agricoles": ["food_crops"],
    "Pacific Community — Centre for Pacific Crops and Trees": ["food_crops", "trees"],
    "National Agricultural Research Institute — Papua New Guinea": ["food_crops", "trees"],
    "INTA — Instituto Nacional de Tecnología Agropecuaria": ["food_crops"],
    "Bolsa de Cereales / grain trade associations": ["food_crops"],
    "Agropalma / palm and tropical oils": ["trees"],
    "Fiocruz — Oswaldo Cruz Foundation": ["human", "insects", "viruses"],
    "ANASAC / Chilean seed multiplication": ["food_crops", "vegetables"],
    "CATIE — tropical agricultural research and genebank": ["trees", "food_crops"],
    "Instituto Nacional de Ciencias Agrícolas": ["food_crops", "microbes"],
    "Indonesian Agency for Agricultural Research and Development": ["food_crops", "trees"],
    "Philippine Rice Research Institute": ["food_crops"],
    "Vietnam Academy of Agricultural Sciences": ["food_crops"],
    "BIOTEC — National Center for Genetic Engineering and Biotechnology": ["food_crops", "fish"],
    "Silal / UAE food security investment": ["food_crops", "vegetables"],
    "King Abdullah University of Science and Technology — desert agriculture": ["food_crops"],
    "National Agricultural Research Organisation — Uganda": ["food_crops", "trees"],
    "Rwanda Agriculture and Animal Resources Development Board": ["food_crops", "livestock"],
    "Instituto de Investigação Agrária de Moçambique": ["food_crops"],
    "Malawi Environmental Affairs Department — biosafety": ["fibre"],
    "Tanzania Commission for Science and Technology": ["food_crops"],
    "Institut de l’Environnement et de Recherches Agricoles": ["fibre", "food_crops"],
    "Conseil du Café-Cacao": ["trees"],
    "Institut de Recherche Agricole pour le Développement": ["food_crops", "trees"],
    "Institut National de la Recherche Agronomique de Tunisie": ["food_crops", "trees"],
    "Institut National de la Recherche Agronomique d’Algérie": ["food_crops"],
    "Cambodian Agricultural Research and Development Institute": ["food_crops"],
    "Nepal Agricultural Research Council": ["food_crops"],
    "ICTA — Instituto de Ciencia y Tecnología Agrícolas": ["food_crops"],
}
